name:                Scrabble
version:             0.1.0.0
github:              "Arminek/Scrabble"
license:             BSD3
author:              "Arkadiusz"
maintainer:          "arkadiusz.k.e@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Learn

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Arminek/Scrabble#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Scrabble-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Scrabble
    - random

tests:
  Scrabble-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Scrabble
    - hspec
    - random
